import os
import json
from time import sleep
from confluent_kafka import Consumer, Producer
from langchain.prompts import PromptTemplate
from langchain_community.chat_models import ChatOpenAI
from dotenv import load_dotenv
import traceback

# === Load .env variables ===
load_dotenv()
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")
KAFKA_USERNAME = os.getenv("KAFKA_USERNAME")
KAFKA_PASSWORD = os.getenv("KAFKA_PASSWORD")
KAFKA_INPUT_TOPIC = os.getenv("KAFKA_INPUT_TOPIC")
KAFKA_OUTPUT_TOPIC = os.getenv("KAFKA_OUTPUT_TOPIC")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

print("[DEBUG] ENV loaded:")
print(" - Input topic:", KAFKA_INPUT_TOPIC)
print(" - Output topic:", KAFKA_OUTPUT_TOPIC)
print(" - API Key found:", bool(OPENROUTER_API_KEY))

if not all([KAFKA_BOOTSTRAP_SERVERS, KAFKA_USERNAME, KAFKA_PASSWORD, KAFKA_INPUT_TOPIC, KAFKA_OUTPUT_TOPIC, OPENROUTER_API_KEY]):
    raise EnvironmentError("❌ Missing required environment variables. Please check .env")

SENTIMENT_LABELS = ["Positive", "Neutral / Follow-up Required", "Negative"]

# === OpenRouter LLM Setup ===
llm = ChatOpenAI(
    model="mistralai/mistral-7b-instruct",
    openai_api_base="https://openrouter.ai/api/v1",
    openai_api_key=OPENROUTER_API_KEY,
    temperature=0.6
)

# === Prompt Templates ===
sentiment_prompt = PromptTemplate(
    input_variables=["notes", "sentiment"],
    template="""
Classify the following cold call notes into one of the following sentiment labels:
{sentiment}

Notes:
{notes}

Return only the label and a brief reason.
"""
)

action_prompt = PromptTemplate(
    input_variables=["notes", "sentiment"],
    template="""
You are a sales assistant for a Kafka-based platform called Condense.

The following are notes from a recent cold call:
"{notes}"

Sentiment label: {sentiment}

Based on this:
- If the sentiment label is "Positive":
  - Carefully read the caller notes and come up with the sales reachout plan step by step which should be customised based on caller notes. Write ready-to-consume reachout and sales plan.

- If the sentiment label is "Follow-up Required" or "Neutral":
  - Check the caller notes.
  - If there are signs of mild interest or open-ended comments, come up with the sales reachout plan step by step. Write ready-to-consume reachout and sales plan.

- If the sentiment label is "Negative":
  - Do not suggest any follow-up. Just say: "No further action recommended based on negative sentiment."

Respond clearly and helpfully.
"""
)

# === Kafka Setup ===
consumer_conf = {
    'bootstrap.servers': KAFKA_BOOTSTRAP_SERVERS,
    'group.id': 'sentiment-analyzer',  # fixed group so offset is remembered
    'auto.offset.reset': 'earliest',   # ensure we get messages even if they came before startup
    'security.protocol': 'SASL_PLAINTEXT',
    'sasl.mechanism': 'SCRAM-SHA-512',
    'sasl.username': KAFKA_USERNAME,
    'sasl.password': KAFKA_PASSWORD,
    'enable.auto.commit': True
}
consumer = Consumer(consumer_conf)
consumer.subscribe([KAFKA_INPUT_TOPIC])
print(f"📡 Subscribed to Kafka topic: {KAFKA_INPUT_TOPIC}")

producer = Producer({
    'bootstrap.servers': KAFKA_BOOTSTRAP_SERVERS,
    'security.protocol': 'SASL_PLAINTEXT',
    'sasl.mechanism': 'SCRAM-SHA-512',
    'sasl.username': KAFKA_USERNAME,
    'sasl.password': KAFKA_PASSWORD
})

# === Main Logic ===
def classify_and_generate(notes):
    try:
        prompt = sentiment_prompt.format(notes=notes, sentiment=', '.join(SENTIMENT_LABELS))
        response = llm.invoke(prompt)
        sentiment = response.content.strip()
        print(f"[LLM] Sentiment: {sentiment}")
    except Exception as e:
        print("[ERROR] Sentiment classification failed.")
        traceback.print_exc()
        return {
            "Caller Notes": notes,
            "Sentiment Label": "Unknown",
            "Reason": f"LLM Error: {e}",
            "Next Action Items": "❌ Skipped"
        }

    if "negative" in sentiment.lower():
        return {
            "Caller Notes": notes,
            "Sentiment Label": sentiment,
            "Reason": "Negative sentiment detected",
            "Next Action Items": "❌ No further action"
        }

    try:
        action_prompt_input = action_prompt.format(notes=notes, sentiment=sentiment)
        result = llm.invoke(action_prompt_input)
        action_items = result.content.strip()
    except Exception as e:
        print("[ERROR] Action plan generation failed.")
        traceback.print_exc()
        action_items = f"❌ Failed: {e}"

    return {
        "Caller Notes": notes,
        "Sentiment Label": sentiment,
        "Reason": "Generated by Mistral",
        "Next Action Items": action_items
    }

# === Kafka Processing Loop ===
try:
    while True:
        msg = consumer.poll(1.0)
        if msg is None:
            continue
        if msg.error():
            print(f"[Kafka Error] {msg.error()}")
            continue

        try:
            payload = json.loads(msg.value().decode('utf-8'))
            if "result" in payload:
                print("⚠️ Skipping already enriched message")
                continue

            notes = payload.get("comments", "").strip()
            if not notes:
                print("⚠️ Skipping empty comment field")
                continue

            print(f"[PROCESSING] Notes: {notes}")
            result = classify_and_generate(notes)
            payload["result"] = result

            enriched = json.dumps(payload).encode("utf-8")
            producer.produce(KAFKA_OUTPUT_TOPIC, enriched)
            producer.flush()
            print(f"✅ Published to {KAFKA_OUTPUT_TOPIC}")
        except Exception as e:
            print(f"[PROCESSING ERROR] {e}")
            traceback.print_exc()
        sleep(0.25)

except KeyboardInterrupt:
    print("🛑 Interrupted by user.")
finally:
    consumer.close()
